### PR TITLE
Don't require git for license check

### LINKED ISSUE #73: check-licenses test fails on release archives
Running `ninja test` on the latest release tarball presents the following error:

```
Traceback (most recent call last):
  File "/build/gtk-layer-shell/src/gtk-layer-shell-0.4.0/test/check-licenses.py", line 156, in <module>
    main()
  File "/build/gtk-layer-shell/src/gtk-layer-shell-0.4.0/test/check-licenses.py", line 121, in main
    all_files = get_important_files()
  File "/build/gtk-layer-shell/src/gtk-layer-shell-0.4.0/test/check-licenses.py", line 99, in get_important_files
    return get_files(get_project_root())
  File "/build/gtk-layer-shell/src/gtk-layer-shell-0.4.0/test/check-licenses.py", line 82, in get_files
    if ignored_by_git(search_path):
  File "/build/gtk-layer-shell/src/gtk-layer-shell-0.4.0/test/check-licenses.py", line 72, in ignored_by_git
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
```

https://github.com/wmww/gtk-layer-shell/blob/4419b65ed8e074ceeff86e61d1c37ebdf6a0f002/test/check-licenses.py#L71

It'd be nice if tests can run without needing to use the git repository.

Thanks!

### PR DESCRIPTION
**Pull request by wmww**
Fixes #73.

*By opening this pull request, I agree for my modifications to be licensed under whatever licenses are indicated at the start of the files I modified*

### CODE REVIEW

**Comment by kloczek** [comment]
Just checked that patch and looks like still it is some issue:
```
[tkloczko@barrel SPECS]$ rpmbuild -ba --with check gtk-layer-shell.spec
warning: Downloading https://github.com/wmww/gtk-layer-shell//commit/b6c2f54b.patch#/gtk-layer-shell-Dont-require-git-for-license-check.patch to /home/tkloczko/rpmbuild/SOURCES/gtk-layer-shell-Dont-require-git-for-license-check.patch
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.urA7X6
+ umask 022
+ cd /home/tkloczko/rpmbuild/BUILD
+ cd /home/tkloczko/rpmbuild/BUILD
+ rm -rf gtk-layer-shell-0.4.0
+ /usr/bin/gzip -dc /home/tkloczko/rpmbuild/SOURCES/gtk-layer-shell-0.4.0.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd gtk-layer-shell-0.4.0
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ /usr/bin/cat /home/tkloczko/rpmbuild/SOURCES/gtk-layer-shell-Dont-require-git-for-license-check.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch
+ RPM_EC=0
++ jobs -p
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.mvyu7a
+ umask 022
+ cd /home/tkloczko/rpmbuild/BUILD
+ cd gtk-layer-shell-0.4.0
+ export 'CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none'
+ CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none'
+ export 'CXXFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none'
+ CXXFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none'
+ export 'FFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules -flto=auto -flto-partition=none'
+ FFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules -flto=auto -flto-partition=none'
+ export 'FCFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules -flto=auto -flto-partition=none'
+ FCFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules -flto=auto -flto-partition=none'
+ export 'LDFLAGS=-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin'
+ LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin'
+ export AR=/usr/bin/gcc-ar RANLIB=/usr/bin/gcc-ranlib NM=/usr/bin/gcc-nm
+ AR=/usr/bin/gcc-ar
+ RANLIB=/usr/bin/gcc-ranlib
+ NM=/usr/bin/gcc-nm
+ export CC=gcc CXX=g++
+ CC=gcc
+ CXX=g++
+ /usr/bin/meson --buildtype=plain --prefix=/usr --libdir=/usr/lib64 --libexecdir=/usr/libexec --bindir=/usr/bin --sbindir=/usr/sbin --includedir=/usr/include --datadir=/usr/share --mandir=/usr/share/man --infodir=/usr/share/info --localedir=/usr/share/locale --sysconfdir=/etc --localstatedir=/var --sharedstatedir=/var/lib --wrap-mode=nodownload --auto-features=enabled . x86_64-redhat-linux-gnu -D docs=true -D examples=false -D tests=true

[..]

Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.QUrvQb
+ umask 022
+ cd /home/tkloczko/rpmbuild/BUILD
+ cd gtk-layer-shell-0.4.0
+ /usr/bin/meson test -C x86_64-redhat-linux-gnu --num-processes 48 --print-errorlogs
ninja: Entering directory `/home/tkloczko/rpmbuild/BUILD/gtk-layer-shell-0.4.0/x86_64-redhat-linux-gnu'
ninja: no work to do.
 1/10 basic-test                           OK             0.82s
 2/10 test-expect-fail                     EXPECTEDFAIL   0.62s
 3/10 test-anchors                         OK             0.67s
 4/10 test-set-layer                       OK             1.22s
 5/10 test-set-size-request                OK             1.47s
 6/10 test-adapts-to-screen-size           OK             1.01s
 7/10 test-auto-exclusive-zone-no-margin   OK             1.41s
 8/10 test-auto-exclusive-zone-with-margin OK             0.82s
 9/10 test-get-version                     OK             0.05s
10/10 check-licenses                       FAIL           0.15s (exit status 1)

Ok:                 8
Expected Fail:      1
Fail:               1
Unexpected Pass:    0
Skipped:            0
Timeout:            0


The output from the failed tests:

10/10 check-licenses                       FAIL           0.15s (exit status 1)

--- command ---
03:58:25 /usr/bin/python3 /home/tkloczko/rpmbuild/BUILD/gtk-layer-shell-0.4.0/test/check-licenses.py
--- stderr ---
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/gtk-layer-shell-0.4.0/test/check-licenses.py", line 156, in <module>
    main()
  File "/home/tkloczko/rpmbuild/BUILD/gtk-layer-shell-0.4.0/test/check-licenses.py", line 121, in main
    all_files = get_important_files()
  File "/home/tkloczko/rpmbuild/BUILD/gtk-layer-shell-0.4.0/test/check-licenses.py", line 99, in get_important_files
    return get_files(get_project_root(), '')
  File "/home/tkloczko/rpmbuild/BUILD/gtk-layer-shell-0.4.0/test/check-licenses.py", line 95, in get_files
    result += get_files(prefix, path.join(search_path, item))
  File "/home/tkloczko/rpmbuild/BUILD/gtk-layer-shell-0.4.0/test/check-licenses.py", line 95, in get_files
    result += get_files(prefix, path.join(search_path, item))
  File "/home/tkloczko/rpmbuild/BUILD/gtk-layer-shell-0.4.0/test/check-licenses.py", line 87, in get_files
    raise RuntimeError('Should not have tried to search a build dir')
RuntimeError: Should not have tried to search a build dir
-------

Full log written to /home/tkloczko/rpmbuild/BUILD/gtk-layer-shell-0.4.0/x86_64-redhat-linux-gnu/meson-logs/testlog.txt
```

**Comment by wmww** [comment]
Hmm, I can not reproduce (I tried starting with the v0.4.0 tarball (which is broken) and applying [the patch](https://github.com/wmww/gtk-layer-shell//commit/b6c2f54b.patch#/gtk-layer-shell-Dont-require-git-for-license-check.patch) (which seems to fix it).

**Comment by kloczek** [comment]
I'm not using dist tar ball but tagged git archive.

**Comment by wmww** [comment]
With #76 you no longer need to explicitly specify to ignore your meson build dir, and this should be completely resolved. I also improved the diagnostic messages.

**Comment by kloczek** [comment]
Still fails wit added as well that patch:
```
[tkloczko@barrel SPECS]$ rpmbuild -ba gtk-layer-shell.spec --with check
warning: Downloading https://github.com/wmww/gtk-layer-shell//commit/b6c2f54b.patch#/gtk-layer-shell-Dont-require-git-for-license-check.patch to /home/tkloczko/rpmbuild/SOURCES/gtk-layer-shell-Dont-require-git-for-license-check.patch
warning: Downloading https://github.com/wmww/gtk-layer-shell//commit/c1808a3b.patch#/gtk-layer-shell-License-check-always-ignore-build-dirs.patch to /home/tkloczko/rpmbuild/SOURCES/gtk-layer-shell-License-check-always-ignore-build-dirs.patch
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.HM21YX
+ umask 022
+ cd /home/tkloczko/rpmbuild/BUILD
+ cd /home/tkloczko/rpmbuild/BUILD
+ rm -rf gtk-layer-shell-0.4.0
+ /usr/bin/gzip -dc /home/tkloczko/rpmbuild/SOURCES/gtk-layer-shell-0.4.0.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd gtk-layer-shell-0.4.0
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ /usr/bin/cat /home/tkloczko/rpmbuild/SOURCES/gtk-layer-shell-Dont-require-git-for-license-check.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch
+ /usr/bin/cat /home/tkloczko/rpmbuild/SOURCES/gtk-layer-shell-License-check-always-ignore-build-dirs.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch

[..]

+ /usr/bin/meson test -C x86_64-redhat-linux-gnu --num-processes 48 --print-errorlogs
ninja: Entering directory `/home/tkloczko/rpmbuild/BUILD/gtk-layer-shell-0.4.0/x86_64-redhat-linux-gnu'
ninja: no work to do.
 1/10 basic-test                           OK             0.82s
 2/10 test-expect-fail                     EXPECTEDFAIL   0.62s
 3/10 test-anchors                         OK             0.60s
 4/10 test-set-layer                       OK             1.27s
 5/10 test-set-size-request                OK             1.42s
 6/10 test-adapts-to-screen-size           OK             1.01s
 7/10 test-auto-exclusive-zone-no-margin   OK             1.42s
 8/10 test-auto-exclusive-zone-with-margin OK             0.81s
 9/10 test-get-version                     OK             0.05s
10/10 check-licenses                       FAIL           0.19s (exit status 1)

Ok:                 8
Expected Fail:      1
Fail:               1
Unexpected Pass:    0
Skipped:            0
Timeout:            0


The output from the failed tests:

10/10 check-licenses                       FAIL           0.19s (exit status 1)

--- command ---
06:03:30 /usr/bin/python3 /home/tkloczko/rpmbuild/BUILD/gtk-layer-shell-0.4.0/test/check-licenses.py
--- stdout ---

The following files are licensed under MIT:
  demo/anchor-control.c
  demo/gtk-layer-demo.c
  demo/gtk-layer-demo.h
  demo/layer-selection.c
  demo/margin-control.c
  demo/menu-bar.c
  demo/monitor-selection.c
  demo/mscl-toggles.c
  demo/version-info.c
  example/example.c
  gtk-priv/h/common.h
  gtk-priv/scripts/ast.py
  gtk-priv/scripts/build.py
  gtk-priv/scripts/config.py
  gtk-priv/scripts/parse.py
  gtk-priv/scripts/repo.py
  gtk-priv/scripts/version.py
  include/gtk-layer-shell.h
  src/custom-shell-surface.c
  src/custom-shell-surface.h
  src/gtk-layer-shell.c
  src/gtk-priv-access.c
  src/gtk-priv-access.h
  src/gtk-wayland.c
  src/gtk-wayland.h
  src/layer-surface.c
  src/layer-surface.h
  src/simple-conversions.c
  src/simple-conversions.h
  src/xdg-popup-surface.c
  src/xdg-popup-surface.h
  src/xdg-toplevel-surface.c
  src/xdg-toplevel-surface.h
  test/mock-server/mock-server.c
  test/mock-server/mock-server.h
  test/mock-server/request-overrides.c
  test/run-integration-test.py
  test/test-client-common/test-client-common.c
  test/test-client-common/test-client-common.h
  test/test-clients/basic-test.c
  test/test-clients/test-adapts-to-screen-size.c
  test/test-clients/test-anchors.c
  test/test-clients/test-auto-exclusive-zone-no-margin.c
  test/test-clients/test-auto-exclusive-zone-with-margin.c
  test/test-clients/test-expect-fail.c
  test/test-clients/test-set-layer.c
  test/test-clients/test-set-size-request.c
  test/tests-not-enabled.py
  test/unit-tests/test-get-version.c

The following files are licensed under LGPLv3:
  gtk-priv/h/gdk_wayland_pointer_data_priv.h
  gtk-priv/h/gdk_wayland_pointer_frame_data_priv.h
  gtk-priv/h/gdk_wayland_seat_priv.h
  gtk-priv/h/gdk_wayland_tablet_data_priv.h
  gtk-priv/h/gdk_wayland_touch_data_priv.h
  gtk-priv/h/gdk_window_impl_class_priv.h
  gtk-priv/h/gdk_window_impl_priv.h
  gtk-priv/h/gdk_window_impl_wayland_class_priv.h
  gtk-priv/h/gdk_window_impl_wayland_priv.h
  gtk-priv/h/gdk_window_priv.h

The following files are licensed under no license:
  debugsources.list
  debugfiles.list
  debuglinks.list
  elfbins.list
  debugsourcefiles.list

No files are licensed under multiple licenses

If some files should be excluded from the license check, add them to test/license-ignore.txt
Failed license check
--- stderr ---
WARNING:__main__:/home/tkloczko/rpmbuild/BUILD/gtk-layer-shell-0.4.0/.git/info/exclude not found, it will not be used to exclude paths from the license check
-------

Full log written to /home/tkloczko/rpmbuild/BUILD/gtk-layer-shell-0.4.0/x86_64-redhat-linux-gnu/meson-logs/testlog.txt
````

**Comment by wmww** [comment]
Now you can just follow the instructions:

> If some files should be excluded from the license check, add them to test/license-ignore.txt

It looks like
```
debugsources.list
debugfiles.list
debuglinks.list
elfbins.list
debugsourcefiles.list
```
should probably all be added. I think this would be better done as a patch rather than upstream change, because it will be different for each packaging system.

**Comment by kloczek** [comment]
Looks like that licence check has nothing to do with checking any functionalities of the generated code of the gtk-layer-shell.

**Comment by wmww** [comment]
Right, you can ignore it entirely if you want. If you patch out the last line of `test/meson.build` it won't run.

**Pull request merged**
