### PR TITLE
Add option to disable examples

### PR DESCRIPTION
**Pull request by ddevault**

### CODE REVIEW

**Comment by wmww** [comment]
Fixes #18

**Comment by wmww** [comment]
Also, can you please set the examples option explicitly in the meson command of the "to install" section of the readme?

**Comment by ddevault** [comment]
I don't think the demo should be installed under any circumstances, so I'm going to nix that unless you disagree.

**Comment by wmww** [comment]
The example probably shouldn't be installed, as it's simply a jumping off point for using the library. The demo, however, is quite useful for testing compositors. I don't see why it shouldn't be installed, especially if it won't e built or installed by default.

**Pull request merged**
