### PR TITLE
Remove pedantic warnings

### LINKED ISSUE #17: -Wpedantic causes stupid warnings
As noted by @raveit65 here: https://github.com/wmww/gtk-layer-shell/issues/4#issuecomment-511020939
```
[15/28] Compiling C object 'demo/2a97516@@gtk-layer-demo@exe/gtk-layer-demo.c.o'.
../demo/gtk-layer-demo.c:27:21: warning: ISO C forbids conversion of function pointer to object pointer type [-Wpedantic]
   27 |         .arg_data = (void *)&layer_option_callback,
      |                     ^
../demo/gtk-layer-demo.c:36:21: warning: ISO C forbids conversion of function pointer to object pointer type [-Wpedantic]
   36 |         .arg_data = (void *)&anchor_option_callback,
      |                     ^
../demo/gtk-layer-demo.c:45:21: warning: ISO C forbids conversion of function pointer to object pointer type [-Wpedantic]
   45 |         .arg_data = (void *)&margin_option_callback,
      |                     ^
```

### PR DESCRIPTION
**Pull request by wmww**
Fixes #17, as suggested by @tristan957 [here](https://github.com/wmww/gtk-layer-shell/issues/4#issuecomment-524340814)

### CODE REVIEW

**Comment by wmww** [comment]
Works on my machine, and doesn't look like anyone else is going to bother to review it

**Comment by ammen99** [comment]
Wouldn't it be better to use `add_project_arguments`?

**Comment by ammen99** [comment]
From meson docs: "Subprojects must not set global arguments because there is no way to do that reliably over multiple subprojects."

Ideally gtk-layer-shell should be packaged, but for now I plan to use it as a subproject until it becomes widely available.

**Comment by wmww** [comment]
If you PR it I'll test it

**Pull request merged**
